import struct
from pathlib import Path

TOMBSTONE = b"__INTERNAL_TOMBSTONE_MARKER__"
DEFAULT_WAL = Path("/tmp/cailloudb-data") / "wal"

WAL_BLOCK_SIZE = 32 * 1024
WAL_HEADER_SIZE = 7
WAL_CRC_STRUCT = struct.Struct(">I")
WAL_PAYLOAD_LEN_STRUCT = struct.Struct(">H")
WAL_SEQ_STRUCT = struct.Struct(">Q")
WAL_LEN_STRUCT = struct.Struct(">I")

WAL_SINGLE_KIND = 0
WAL_BATCH_KIND_FULL = 1
WAL_BATCH_KIND_FIRST = 2
WAL_BATCH_KIND_MIDDLE = 3
WAL_BATCH_KIND_LAST = 4

MEMTABLE_MAX_BYTES_SIZE = 32 * 1024 * 1024

# Internal Key
# Used for _SkipListNode & SSTable encoding
INTERNAL_KEY_LEN_STRUCT = struct.Struct("<I")
INTERNAL_KEY_METADATA_STRUCT = struct.Struct(">Q")
INTERNAL_KEY_VALUE_TYPE_DELETE = 0x0
INTERNAL_KEY_VALUE_TYPE_PUT = 0x1
INTERNAL_KEY_MAX_SEQ_NUM = (1 << 56) - 1
INTERNAL_KEY_LEN_METADATA = 8

# SSTable file encoding
SSTABLE_FOOTER_STRUCT = struct.Struct(">QQI")
SSTABLE_MAX_FILE_SIZE = 64 * 1024 * 1024
SSTABLE_INDEX_BLOCK_OFFSET_AND_LEN_STRUCT = struct.Struct(">QQ")
SSTABLE_MAGIC_NUMBER = 0x4341494C

# SSTable Block encoding
SSTABLE_BLOCK_VALUE_LEN_STRUCT = struct.Struct("<I")
SSTABLE_BLOCK_DEFAULT_SIZE = 4096  # 4 KB
