import struct
from pathlib import Path

TOMBSTONE = b"__INTERNAL_TOMBSTONE_MARKER__"
DEFAULT_WAL = Path("/tmp/cailloudb-data") / "wal"
MEMTABLE_MAX_BYTES_SIZE = 32 * 1024 * 1024

# Internal Key
# Used for _SkipListNode & SSTable encoding
INTERNAL_KEY_LEN_STRUCT = struct.Struct("<I")
INTERNAL_KEY_METADATA_STRUCT = struct.Struct(">Q")
INTERNAL_KEY_VALUE_TYPE_DELETE = 0x0
INTERNAL_KEY_VALUE_TYPE_PUT = 0x1
INTERNAL_KEY_MAX_SEQ_NUM = (1 << 56) - 1
INTERNAL_KEY_LEN_METADATA = 8

# SSTable file & encoding
SSTABLE_FOOTER_STRUCT = struct.Struct(">QQI")
SSTABLE_MAX_FILE_SIZE = 64 * 1024 * 1024
SSTABLE_INDEX_BLOCK_OFFSET_AND_LEN_STRUCT = struct.Struct(">QQ")
SSTABLE_MAGIC_NUMBER = 0x4341494C
SSTABLE_L0_COMPACTION_TRIGGER = 4
SSTABLE_L1_MAX_BYTES = 10 * 1024 * 1024
SSTABLE_MAX_LEVELS = 7
SSTABLE_LEVEL_MULTIPLIER = 10

# SSTable Block encoding
SSTABLE_BLOCK_VALUE_LEN_STRUCT = struct.Struct("<I")
SSTABLE_BLOCK_DEFAULT_SIZE = 4096  # 4 KB
